---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
  - name: centos-6.7
  - name: centos-7.2
suites:
  - name: cobbler_source_build
    run_list:
      - 'recipe[cobblerd::cobbler_source]'
      - 'recipe[cobblerd::default]'
  - name: cobbler_package_install
    run_list:
      - 'recipe[cobblerd::cobbler_package]'
      - 'recipe[cobblerd::default]'
  - name: cobbler_source_images
    run_list:
      - 'recipe[cobblerd::cobbler_source]'
      - 'recipe[cobblerd::default]'
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: cobbler_package_images
    run_list:
      - 'recipe[cobblerd::cobbler_package]'
      - 'recipe[cobblerd::default]'
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: syslinx_source
    run_list:
      - 'recipe[cobblerd::syslinux_source]'
  - name: syslinx_package
    run_list:
      - 'recipe[cobblerd::syslinux_package]'
    excludes:
      - centos-5.11
