---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - 'recipe[apt::default]'
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2
  - name: centos-5.11
    attributes:
      cobbler:
        packages:
          - cobbler

suites:
  - name: default
    run_list:
      - 'recipe[cobblerd::default]'
  - name: apache2
    run_list:
      - 'recipe[cobblerd::default]'
    attributes:
      cobbler:
        include_apache2: true
  - name: images
    run_list:
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: web
    run_list:
      - 'recipe[cobblerd::web]'
    excludes:
      - centos-5.11
