---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
suites:
  - name: cobbler_source_build
    attributes: {
      cobbler: {
        clean_up_build: false
      }
    }
    run_list:
      - 'recipe[cobblerd::cobbler_source_build]'
      - 'recipe[cobblerd::cobbler_source_install]'
      - 'recipe[cobblerd::default]'
  - name: cobbler_package_install
    run_list:
      - 'recipe[cobblerd::cobbler_package]'
      - 'recipe[cobblerd::default]'
  - name: cobbler_source_images
    run_list:
      - 'recipe[cobblerd::cobbler_source_install]'
      - 'recipe[cobblerd::cobbler_source_build]'
      - 'recipe[cobblerd::default]'
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: cobbler_package_images
    run_list:
      - 'recipe[cobblerd::cobbler_package]'
      - 'recipe[cobblerd::default]'
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: syslinx_source
    run_list:
      - 'recipe[cobblerd::syslinux_source]'
  - name: syslinx_package
    run_list:
      - 'recipe[cobblerd::syslinux_package]'
