node.default['cobblerd']['http']['server_name'] = 'localhost'
node.default['cobblerd']['http']['dhparams_file'] = '/etc/nginx/dhparam.pem'

# node.default['cobblerd']['http']['ssl_certificate_file']     = "/etc/pki/tls/certs/#{node.default['cobblerd']['http']['server_name']}.crt"
# node.default['cobblerd']['http']['ssl_certificate_key_file'] = "/etc/pki/tls/private/#{node.default['cobblerd']['http']['server_name']}.key"

node.default['cobblerd']['settings']['allow_duplicate_hostnames'] = 0
node.default['cobblerd']['settings']['allow_duplicate_ips'] = 0
node.default['cobblerd']['settings']['allow_duplicate_macs'] = 0
node.default['cobblerd']['settings']['allow_dynamic_settings'] = 0
node.default['cobblerd']['settings']['anamon_enabled'] = 0
node.default['cobblerd']['settings']['authn_pam_service'] = 'login'
node.default['cobblerd']['settings']['auth_token_expiration'] = 3600
node.default['cobblerd']['settings']['build_reporting_enabled'] = 0
node.default['cobblerd']['settings']['build_reporting_sender'] = ''
# Make sure to wrap the elements in single quotes so that the output works properly in the ERB template.
node.default['cobblerd']['settings']['build_reporting_email'] = %w['root@localhost'] # rubocop:disable Lint/PercentStringArray
node.default['cobblerd']['settings']['build_reporting_smtp_server'] = 'localhost'
node.default['cobblerd']['settings']['build_reporting_subject'] = ''
node.default['cobblerd']['settings']['build_reporting_ignorelist'] = %w[""]
node.default['cobblerd']['settings']['cheetah_import_whitelist'] = %w[random re time]
node.default['cobblerd']['settings']['createrepo_flags'] = '-c cache -s sha'
node.default['cobblerd']['settings']['default_kickstart'] = '/var/lib/cobbler/kickstarts/default.ks'
node.default['cobblerd']['settings']['default_name_servers'] = %w[]
node.default['cobblerd']['settings']['default_ownership'] = %w[admin]
node.default['cobblerd']['settings']['default_password_crypted'] = '$1$mF86/UHC$WvcIcX2t6crBz2onWxyac.'
node.default['cobblerd']['settings']['default_template_type'] = 'cheetah'
node.default['cobblerd']['settings']['default_virt_bridge'] = 'xenbr0'
node.default['cobblerd']['settings']['default_virt_file_size'] = '5'
node.default['cobblerd']['settings']['default_virt_ram'] = '512'
node.default['cobblerd']['settings']['default_virt_type'] = 'xenpv'
node.default['cobblerd']['settings']['enable_gpxe'] = '0'
node.default['cobblerd']['settings']['enable_menu'] = '1'
node.default['cobblerd']['settings']['func_auto_setup'] = '0'
node.default['cobblerd']['settings']['func_master'] = 'overlord.example.org'
node.default['cobblerd']['settings']['http_port'] = '80'
node.default['cobblerd']['settings']['kernel_options'] = { 'ksdevice' => 'bootif', 'lang' => "' '", 'text' => '~' }
node.default['cobblerd']['settings']['kernel_options_s390x'] = { 'RUNKS' => '1',
                                                                 'ramdisk_size' => '40000',
                                                                 'root' => '/dev/ram0',
                                                                 'ro' => '~',
                                                                 'ip' => 'off',
                                                                 'vnc' => '~' }
node.default['cobblerd']['settings']['ldap_server'] = 'ldap.example.com'
node.default['cobblerd']['settings']['ldap_base_dn'] = 'DC=example,DC=com'
node.default['cobblerd']['settings']['ldap_port'] = '389'
node.default['cobblerd']['settings']['ldap_tls'] = '1'
node.default['cobblerd']['settings']['ldap_anonymous_bind'] = '1'
node.default['cobblerd']['settings']['ldap_search_bind_dn'] = ''
node.default['cobblerd']['settings']['ldap_search_passwd'] = ''
node.default['cobblerd']['settings']['ldap_search_prefix'] = 'uid='
node.default['cobblerd']['settings']['ldap_tls_cacertfile'] = ''
node.default['cobblerd']['settings']['ldap_tls_keyfile'] = ''
node.default['cobblerd']['settings']['ldap_tls_certfile'] = ''
node.default['cobblerd']['settings']['mgmt_classes'] = %w[]
node.default['cobblerd']['settings']['mgmt_parameters'] = { 'from_cobbler' => 1 }
node.default['cobblerd']['settings']['puppet_auto_setup'] = '0'
node.default['cobblerd']['settings']['sign_puppet_certs_automatically'] = '0'
node.default['cobblerd']['settings']['puppetca_path'] = '/usr/bin/puppet'
node.default['cobblerd']['settings']['remove_old_puppet_certs_automatically'] = '0'
node.default['cobblerd']['settings']['manage_dhcp'] = '0'
node.default['cobblerd']['settings']['manage_dns'] = '0'
node.default['cobblerd']['settings']['bind_chroot_path'] = ''
node.default['cobblerd']['settings']['bind_master'] = node['name']
node.default['cobblerd']['settings']['manage_tftpd'] = '1'
node.default['cobblerd']['settings']['manage_rsync'] = '0'
node.default['cobblerd']['settings']['manage_forward_zones'] = %w[]
node.default['cobblerd']['settings']['manage_reverse_zones'] = %w[]
node.default['cobblerd']['settings']['next_server'] = node['name']
node.default['cobblerd']['settings']['power_management_default_type'] = 'ipmitool'
node.default['cobblerd']['settings']['power_template_dir'] = '/etc/cobbler/power'
node.default['cobblerd']['settings']['pxe_just_once'] = '0'
node.default['cobblerd']['settings']['pxe_template_dir'] = '/etc/cobbler/pxe'
node.default['cobblerd']['settings']['consoles'] = '/var/consoles'
node.default['cobblerd']['settings']['redhat_management_type'] = 'off'
node.default['cobblerd']['settings']['redhat_management_server'] = 'xmlrpc.rhn.redhat.com'
node.default['cobblerd']['settings']['redhat_management_key'] = ''
node.default['cobblerd']['settings']['redhat_management_permissive'] = '0'
node.default['cobblerd']['settings']['register_new_installs'] = '0'
node.default['cobblerd']['settings']['reposync_flags'] = '-l -n -d'
node.default['cobblerd']['settings']['restart_dns'] = '1'
node.default['cobblerd']['settings']['restart_dhcp'] = '1'
node.default['cobblerd']['settings']['run_install_triggers'] = '1'
node.default['cobblerd']['settings']['scm_track_enabled'] = '0'
node.default['cobblerd']['settings']['scm_track_mode'] = 'git'
node.default['cobblerd']['settings']['server'] = node['name']
node.default['cobblerd']['settings']['client_use_localhost'] = '0'
node.default['cobblerd']['settings']['client_use_https'] = '0'
node.default['cobblerd']['settings']['snippetsdir'] = '/var/lib/cobbler/snippets'
node.default['cobblerd']['settings']['template_remote_kickstarts'] = '0'
node.default['cobblerd']['settings']['virt_auto_boot'] = '1'
node.default['cobblerd']['settings']['webdir'] = '/var/www/cobbler'
node.default['cobblerd']['settings']['xmlrpc_port'] = '25151'
node.default['cobblerd']['settings']['yum_post_install_mirror'] = '1'
node.default['cobblerd']['settings']['yum_distro_priority'] = '1'
node.default['cobblerd']['settings']['yumdownloader_flags'] = '--resolve'
node.default['cobblerd']['settings']['serializer_pretty_json'] = '0'
node.default['cobblerd']['settings']['replicate_rsync_options'] = '-avzH'
node.default['cobblerd']['settings']['replicate_repo_rsync_options'] = '-avzH'
node.default['cobblerd']['settings']['always_write_dhcp_entries'] = '0'
node.default['cobblerd']['settings']['proxy_url_ext'] = ''
node.default['cobblerd']['settings']['proxy_url_int'] = ''
